-- 030_processed_events_event_id_uuid.sql
-- Align events.processed_events.event_id type with events.events.id (UUID).
-- Historically the PK / filter joins compared UUID with TEXT — Postgres
-- rejects that with "operator does not exist: uuid = text", which broke
-- the consumer "already processed" filter and caused duplicate event
-- processing.
--
-- All existing event_id values are valid UUIDs (generated by randomUUID()).
-- Idempotent for fresh + legacy DBs.


BEGIN;


-- Drop the composite PK so we can change the column type, then recreate.
DO $$
DECLARE
  pk_name text;
BEGIN
  SELECT c.conname INTO pk_name
  FROM pg_constraint c
  JOIN pg_class t ON t.oid = c.conrelid
  JOIN pg_namespace n ON n.oid = t.relnamespace
  WHERE n.nspname = 'events'
    AND t.relname = 'processed_events'
    AND c.contype = 'p';
  IF pk_name IS NOT NULL THEN
    EXECUTE 'ALTER TABLE events.processed_events DROP CONSTRAINT ' || quote_ident(pk_name);
  END IF;
END$$;


-- Change column type only if it's not already uuid.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'events'
      AND table_name = 'processed_events'
      AND column_name = 'event_id'
      AND data_type <> 'uuid'
  ) THEN
    ALTER TABLE events.processed_events
      ALTER COLUMN event_id TYPE UUID USING event_id::uuid;
  END IF;
END$$;


-- Recreate the composite PK if it's not present.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE n.nspname = 'events'
      AND t.relname = 'processed_events'
      AND c.contype = 'p'
  ) THEN
    ALTER TABLE events.processed_events
      ADD PRIMARY KEY (event_id, consumer_name);
  END IF;
END$$;


COMMIT;